05 01 tooltip
js-tasks-ru/htmlcss-20210916_chagdurova1992 pull request #11
Opened 2021-10-11 13:09 UTC by norzhima-m

2021-10-11 13:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-11 19:15 UTC, GSemikozov requested changes

2021-10-11 19:15 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip-page {
это. по традиции уносит в тег style самой страницы с решением)

2021-10-11 19:15 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%, -160%);
лучше не применять здесь 160% (привязываемся к размеру иконки - а если она будет в 5 раз больше, то тогда и всплывашка улетит в 5 раз выше))). Важно чтобы отступ от всплывашки до триггера всегда был одинаковый, сделать это можно так: bottom: 100%; transform: translate(-50%, -13px);

2021-10-12 11:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-12 11:35 UTC, norzhima-m commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip-page {
вынесла

2021-10-12 11:35 UTC, norzhima-m commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%, -160%);
пофиксила

2021-10-12 11:38 UTC, GSemikozov approved these changes

2021-10-12 11:38 UTC, merged