03 home page
js-tasks-ru/htmlcss-20210916_chagdurova1992 pull request #3
Opened 2021-09-24 13:16 UTC by norzhima-m

2021-09-24 13:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-24 14:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-26 11:47 UTC, GSemikozov requested changes

2021-09-26 11:47 UTC, GSemikozov commented on components/footer/footer.css
> +    background-color: white;
цвета забираем из переменных )

2021-09-26 11:47 UTC, GSemikozov commented on components/footer/footer.css
> +    height: 384px;
это временно чисто под этот ПР, пока внутри нет контента?

2021-09-26 11:47 UTC, GSemikozov commented on components/footer/footer.css
> +    height: 384px;
хотя нет, контент-то есть. Фиксировать высоту не надо)

2021-09-26 11:47 UTC, GSemikozov commented on components/header/header.css
> +    height: 237px;
и тут

2021-09-26 11:47 UTC, GSemikozov commented on components/header/header.css
> +    background-color: white;
цвет - заберем из переменных

2021-09-26 11:47 UTC, GSemikozov commented on components/preview/preview.css
> +    height: 1036px;
не будем фиксировать высоту

2021-09-26 11:47 UTC, GSemikozov commented on components/preview/preview.css
> +    background-color: #F9FAFC;
заберем из переменных

2021-09-26 12:34 UTC, norzhima-m commented on components/footer/footer.css
> +    background-color: white;
готово

2021-09-26 12:34 UTC, norzhima-m commented on components/footer/footer.css
> +    height: 384px;
убрала фиксацию высоты

2021-09-26 12:34 UTC, norzhima-m commented on components/header/header.css
> +    height: 237px;
готово

2021-09-26 12:34 UTC, norzhima-m commented on components/header/header.css
> +    background-color: white;
добавила переменную

2021-09-26 12:34 UTC, norzhima-m commented on components/preview/preview.css
> +    height: 1036px;
убрала

2021-09-26 12:35 UTC, norzhima-m commented on components/preview/preview.css
> +    background-color: #F9FAFC;
создала переменную и добавила ее в preview.css

2021-09-26 12:43 UTC, GSemikozov approved these changes

2021-09-26 12:43 UTC, merged