03 01 button
js-tasks-ru/htmlcss-20210916_chagdurova1992 pull request #4
Opened 2021-09-25 16:31 UTC by norzhima-m

2021-09-25 16:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-26 11:49 UTC, GSemikozov requested changes

2021-09-26 11:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
и еще обязательно pointer-events: none

2021-09-26 11:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
transition можно задать сразу на уровне .button

2021-09-26 11:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
модификаторы пишутся через одно нижнее подчеркивание, через два - это уже элемент блока)

2021-09-26 19:21 UTC, norzhima-m commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
добавила

2021-09-26 19:21 UTC, norzhima-m commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
перенесла

2021-09-26 19:22 UTC, norzhima-m commented on 03-lection1/01-button/button.css
> +.button__primary {
исправила на одно нижнее подчеркивание

2021-09-27 14:06 UTC, GSemikozov approved these changes

2021-09-27 14:06 UTC, merged