solution 04-01-histogram
js-tasks-ru/htmlcss-20210916_chagdurova1992 pull request #7
Opened 2021-09-29 13:40 UTC by norzhima-m

2021-09-29 13:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-29 19:37 UTC, GSemikozov requested changes

2021-09-29 19:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    grid-template-rows: 30% 1fr;
первый роу наверно лучше сделать auto

2021-09-29 19:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +p, h4 {
общие сбросы?) тогда уносим в normalize.css или main.css

2021-09-29 19:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-grow: 30;
можно просто 1) но - это будет работать только если у компонента фиксированная высота + контента в хедере не будет больше. Правильнее будет задать высоту чарту как в дизайне 50px а также добавить отступ сверху

2021-09-29 19:37 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 1px;
margin-right

2021-09-30 12:51 UTC, norzhima-m commented on 04-lection2/01-histogram/histogram.css
> +    grid-template-rows: 30% 1fr;
заменила на авто

2021-09-30 12:51 UTC, norzhima-m commented on 04-lection2/01-histogram/histogram.css
> +p, h4 {
вынесла в main

2021-09-30 12:52 UTC, norzhima-m commented on 04-lection2/01-histogram/histogram.css
> +    flex-grow: 30;
готово

2021-09-30 12:52 UTC, norzhima-m commented on 04-lection2/01-histogram/histogram.css
> +    margin: 1px;
заменила на margin-right

2021-10-01 07:45 UTC, GSemikozov requested changes

2021-10-01 07:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.header__left {
видимо я не обратил. внимание в прошлый раз, но - в histogram мы не можем описывать другие блоки, такие как header, graph, column. Это на самом деле элементы histogram,  поэтому структура классов будет выглядеть так:
header -> .histogram__header
.header__name -> histogram__title
.header__a -> .histogram__link
.header__number -> .histogram__amount
.header__right -> .histogram__header-col
.graph -> .histogram__graph
.graph__column -> .histogram__graph-column
.column_height-10 -> .histogram__graph-column_10 и т.д.

2021-10-01 20:09 UTC, norzhima-m commented on 04-lection2/01-histogram/histogram.css
> +.header__left {
пофикшено

2021-10-02 16:23 UTC, GSemikozov approved these changes

2021-10-02 16:23 UTC, merged